# Generated by Django 5.1.2 on 2024-11-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_estado_pedido_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='FechaRegistro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
