# Generated by Django 5.1.2 on 2024-11-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_fecharegistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
